unikernel: build
	cp dist/qubes-firewall.xen dist/qubes-firewall.xen.debug
	strip dist/qubes-firewall.xen
	cp dist/qubes-firewall.xen .
	sha256sum qubes-firewall.xen

fetchmotron: qubes_firewall.xen
	test-mirage qubes_firewall.xen mirage-fw-test &
	sleep 1
	boot-mirage fetchmotron
