tar: build
	rm -rf _build/mirage-firewall
	mkdir _build/mirage-firewall
	cp qubes_firewall.xen _build/mirage-firewall/vmlinuz
	touch _build/mirage-firewall/modules.img
	cat /dev/null | gzip -n > _build/mirage-firewall/initramfs
	tar cjf mirage-firewall.tar.bz2 -C _build --mtime=./build-with-docker.sh mirage-firewall

fetchmotron: qubes_firewall.xen
	test-mirage qubes_firewall.xen mirage-fw-test &
	sleep 1
	boot-mirage fetchmotron
