name: Main workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./build-with-docker.sh

      - name: Verify
        run: |
          sh -exc 'if [ $(sha256sum dist/qubes-firewall.xen | cut -d " " -f 1) = $(grep "SHA2 last known" build-with-docker.sh | rev | cut -d ":" -f 1 | rev | cut -d "\"" -f 1 | tr -d " ") ]; then echo "SHA256 MATCHES"; else exit 42; fi'
          echo '### sha256' >> $GITHUB_STEP_SUMMARY
          sh -exc 'sha256sum dist/qubes-firewall.xen >> $GITHUB_STEP_SUMMARY'
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mirage-firewall.tar.bz2
          path: mirage-firewall.tar.bz2
